# Generated by Django 4.2.7 on 2025-07-18 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connection_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_type', models.CharField(choices=[('dashboard', 'Dashboard Monitor'), ('search', 'Search Session'), ('admin', 'Admin Panel')], default='dashboard', max_length=50)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'websocket_connections',
                'ordering': ['-connected_at'],
            },
        ),
        migrations.CreateModel(
            name='RealtimeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('scholarship_found', 'Scholarship Found'), ('website_discovered', 'Website Discovered'), ('ai_thinking', 'AI Thinking'), ('search_progress', 'Search Progress'), ('error_occurred', 'Error Occurred'), ('session_update', 'Session Update')], db_index=True, max_length=50)),
                ('event_data', models.JSONField(default=dict)),
                ('message', models.TextField(blank=True)),
                ('broadcast_to_all', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_count', models.IntegerField(default=0)),
                ('target_connections', models.ManyToManyField(blank=True, related_name='targeted_events', to='realtime.websocketconnection')),
            ],
            options={
                'db_table': 'realtime_events',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['event_type', 'sent_at'], name='realtime_ev_event_t_5804ec_idx')],
            },
        ),
    ]
